### ISSUE TITLE
Games with long names overlap mode

### ISSUE THREAD

**Issue by cucholix** [masagrator/ReverseNX-Tool#5]
Games with long names like "Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition" overlaps the mode selection, making impossible to see what mode is currently set.
![reversenx_overlap](https://user-images.githubusercontent.com/16081693/93720962-115f1700-fb63-11ea-971e-5a2ad1a344b7.jpg)

**Comment by pixeltester** [comment]
This is a Borealis issue really, it happens with all homebrew using this library https://github.com/natinusala/borealis

**Comment by cucholix** [comment]
Could it possible force the character length to display a fixed number of characters?

**Comment by masagrator** [comment]
There is already PR for fixing this issue. Dunno how many days it will take until it will be reviewed and merged

**Comment by masagrator** [comment]
Issue is also mitigated with my custom text scaling solution.

For now issue is staying open because now only issue is with long titles using only capital letters which needs more aggressive scaling. Example:
![image](https://user-images.githubusercontent.com/8557858/94344216-0c480f00-001e-11eb-9699-a5da4a2fb11d.png)

**Comment by masagrator** [comment]
Ok, I think I have done enough to mitigate issue. Closing. :P
